### ISSUE TITLE
ValueSets based on SNOMED and SNOMED refsets

### ISSUE THREAD

**Issue by rlindstrm** [rlindstrm/TS-implementation#6]
1) Maintaining value sets as refsets (workflow from SNOMED tooling to TS)
2) VS using an old versions of SNOMED, which I don't have in my TS. Throws errors/warnings in mappings.

**Comment by rlindstrm** [comment]
3. ValueSets that use SNOMED but have extra information (different hierachy from SNOMED's, or additional data). 
These VSs should use codesystem supplement as their base.

**Comment by dionmcm** [comment]
Hi @rlindstrm, I've been trying to get my head around this so I have more questions than answers at this point...sorry.

Am I right in saying the current process has authoring in 2 places
- The Refset Tool - SNOMED International's Managed Service offering?
- CSV files - hand edited?

Are these managed by different sets of people, or is it the same people who edit the reference sets in the Refset Tool and the CSV files?

Which is considered the source of truth? Is one created from the other? Presumably they are supposed to match?

Probably more importantly, what is the desired state? Seems like you'd like to author these reference sets in the Refset Tool, but then manage the other contextual properties the CSV files add somewhere else?

What about from an implementation standpoint. Is the desire to move from these CSV files to FHIR resources/services and deprecate the CSV files, or have both? I'm trying to get my head around which is the primary authoring form and which is the primary implementation/use form of the data.

If the CSV files are to stay and you like your authoring process now (which it sounds like you don't?), then you can engineer a process to convert the CSV files to FHIR resources once you figure out the right mapping between them and FHIR. Bearing in mind the possibly different users of the CSV files versus the FHIR rendering, not all of the properties in the CSV file may need to be carried into the FHIR rendering.

If you want to ditch the CSV files as an authoring process and move to FHIR resources, that's possible too. But you'd likely need to consider creating some tooling to author/manage those resources. CSVs/spreadsheets are great in a way because there's already tools to view and manipulate them. There are tools like Snapper, but it is a general purpose and relatively simple tool that's likely to be unwieldy for a set of properties like these CSV files, depending on how they manifest as FHIR resources. If you want to keep the CSV publication format you'd also need to create a process to turn the FHIR resources into that CSV format.

In terms of the mapping to FHIR resources, this depends mostly on who is going to use this data from the FHIR API (as opposed to the CSV files if they are staying long term), and what they need. Typically not all fields in the source file are needed for every use case, and not all users implement every use case - so there is likely a subset of the properties that you would sensibly port to a FHIR representation. Trying to port everything because it is there often ends up with compromises which might affect usability of the key use cases for data that might not be needed at all - for example the last updated and comments fields.

So I think the first thing to figure out is who uses this data and what do they need to do with it, or just how do they currently use it. That can be mapped on to different options for FHIR resources and sets of FHIR operations that can achieve those needs. Some of those options might make some use cases easier at the expense of others, so from that you can pick the option that represents the best trade off for your users.

Most of this to me looks like properties annotated onto codes in the context of a ValueSet - I know you won't like it but that looks a lot like a CodeSystem Supplement used in the context of a ValueSet. The only other way that occurs to me of doing this is with ConceptMaps which feels ugly.

The hierarchical properties are interesting, but I don't think there's a way to override the hierarchy from the base code system, in this case SNOMED CT. So I'd suggest that the way to handle them is more or less the way the CSV does - just as extra properties which the user of the data has to understand exists in the context of this ValueSet and knows what to do with it. Do you have any more information on how these hierarchical properties (parent/level) are used?

In terms of these goals

> We can be sure that all concepts used in value sets are translated in SNOMED Estonian extension.

I don't think there's a server side way to do this. But you can write a fairly simple script that expands the ValueSet with designations and looks for a match between the display and designations for each concept ensuring the display matches a designation that has an Estonian language code. That would tell you if any of them don't, and would work with any ValueSet, even implicit ValueSets.

> We can be sure that the value sets we use can be successfully validated against the most recent Estonian extension.

By validated do you mean doesn't contain inactive codes from the most recent Estonian extension? Again I don't think there's server side functionality for that because it is legitimate for an inactive concept to be in a ValueSet. But you could have a script that expands the ValueSet with activeOnly=false and then check to see if any returned members are inactive.

So both of these cases I don't think the FHIR server can do these for you, but it has services that you could script around to check these conditions.

**Comment by rlindstrm** [comment]
Answering your questions first.

**Currently:**

- We have two places for authoring: refset tool, and handmade CSV. Ideally, the content should match.
- Refsets and CSVs are handled by the same people.
- CSV is considered the source of truth for users. Technically, refsets are created/updated before CSV.
- Refsets don't include inactive concepts, value sets include all history (but inactive snomed concepts go into inactive status in the value set).

**The goal:**

- Create a new terminology management system. This thread here is a part of gathering the requirements for it actually. We will also keep using SNOMED Managed Service tooling.
- Have a seamless workflow for creating value sets based on SNOMED. We want to choose the preferred display names, add custom hierarchy, and possibly other comments.
- It is negotiable if we want to keep publishing value sets as refsets. I believe they are not used by anyone but ourselves, but so far it's been extremely helpful to have them - duplicate work, but the only way to ensure quality in our CSV-management. It's also worth considering, if we could just use local sets in refset tool to reach the same result, but possibly it would not make anything easier.
- No handmade CSVs in the future.
- Source of truth would be the FHIR value set published in the terminology server.

**Hierachy**
Custom hierachies in our SNOMED value sets are used as groupers, mostly used in the UIs for prettier dropdowns and easier filtering. SNOMED hierachy is IS-A relationships, so I'd say they're not necessarily conflicting in meaning. 

It's also worth noting that we as an organisation are not only creating these value sets, but we also have to use them ourselves (in queries and UIs both). :)

Michael mentioned that we can define the expansion explicitly in the ValueSet. I think that would help us with the custom hierarchy and other stuff that would "normally" be in the CodeSystem Supplement or impossible.

**Comment by dionmcm** [comment]
So I think it is great that you hav the people that do the resets and the CSVs and people that use the sets in queries and UIs - that means you've got direct access to a set of people that cover authoring and usage use cases. It also means you've got complete control of the authoring processes since you own both the reset and the CSVs. Those are very good things.

>No handmade CSVs in the future.
>Source of truth would be the FHIR value set published in the terminology server.

I'm reading that as moving from the CSVs to FHIR ValueSets published in the terminology server, i.e. the CSVs eventually won't be published. To achieve FHIR ValueSets as the source of truth, will you need to have a period where the CSVs are published generated from the FHIR ValueSets? Or can you decommission the CSVs and swap to the FHIR ValueSets in one go? The reason for the question is that the FHIR ValueSets will need sufficient parity to generate the CSVs in that case, or close enough (maybe not all the columns if they aren't all necessary).

Unfortunately unless Michael has better suggestions, I don't think the tooling you need exists - i.e. the user interfaces to author and maintain the FHIR ValueSets. As I said Snapper is a general purpose simple tool, I think it would be unwieldy for this task.

How do you manage the reference set in the Refset tool? Is it ECL or just an enumeration of concepts? I imagine the refset tool is helping you see when concepts in the set become inactive and find replacements, as well as see where Estonian translation is needed? Or is the value the Refset tool is giving your for authoring in parallel different to my assumptions?

The reason I ask is that a separate tool, even based off the FHIR terminology server, could manage these things. It could show you where you've got inactive concepts in your refset/s a SNOMED CT upgrade, and even detect where there are missing translations. You could manage that by ECL if that was convenient or an enumerated list....of course these are just thoughts.

I don't think you _need_ the reference sets published if you have the ValueSets, and you might not need them at all if the tooling/process you create covers off the benefits that using the Refset tool to create them in parallel currently gives you, which I think it could.

So you drill down from the custom hierarchy level to the concept/s? You could do that using a filter on a property for members of the ValueSet. Or you could even use a ConceptMap to map from the custom hierarchy concepts to the concepts "in" each of the levels and add the additional values as ConceptMap "products". You could also create an "expansion only ValueSet" that contained all the precomputed expansion with the desired hierarchy in it the way Michael said. But then it appears that Parent code and Hierarchy Level aren't always populated?

I'm not really sure what the trade offs are. I think it might take more understanding of how Parent code and Hierarchy level are actually used in the queries and UI. For example in the UI is the top level of the list to select from the concepts that don't have a Parent code and the unique set of Parent codes, and if someone picks a Parent code from the list they are shown the concepts with that Parent code? That sort of interaction detail would allow us to break it down to the set requests you'd have to make to achieve that functionality and how that might work with the various options in FHIR (ValueSets, ConceptMaps, expansion only ValueSets etc).

Finally the inactive concepts are interesting. So there's a few possible states

1. active concept active in the value set
2. active concept inactive in the value set
3. inactive concept active in the value set
4. inactive concept inactive in the value set

I assume number 3 is invalid as you don't want inactive concepts in the value set. Is number 2 valid? Possibly a concept incorrectly included and the inactive status in the value set shows it _was_ in the value set at some point?

ValueSets can contain active and inactive concepts, that's no problem but the membership of that concept in the ValueSet doesn't have an inactive/active status - it is either in the ValueSet or not, it isn't in with an inactive status. You could achieve this a few ways

1. concepts (active or inactive) come and go from one version of the ValueSet to the next, and the concepts that were previously in a ValueSet will be present in a prior version of the ValueSet resource (or its expansion)
2. the ValueSets always grow and once a concept is in one version it is in every future version active or inactive. You can expand a ValueSet and request inactive concepts be included or omitted from the expansion result, so that would allow users to see or not see them
3. as per number 2 but you also include a "status" property for each ValueSet member indicating if it is active or inactive in the context of the ValueSet, then you'll have the full set of 4 possible states I listed above

Again I think you need to drill into how these inactive/active statuses are used to figure out what would be best for those consuming them. You may need to represent more than that to drive your authoring workflow, but I'd suggest first figuring out the minimum needed for the implementers using the data and work back from there.

**Comment by rlindstrm** [comment]
Continues here: https://github.com/TEHIK-EE/terminology-migration/issues/2
